### ISSUE TITLE
Can't save Buck ground Color

### ISSUE THREAD

**Issue by AkihiroTokai** [Aogon/TimeTable#1]
【概要】土曜日2限以降の背景色が保存できない。
【再現方法】Campの進捗もあるので後ほど確認します。
【特記事項】なし

**Comment by AkihiroTokai** [comment]
@Aogon SettingからCollaboraterに追加してもらえるとありがたいです！

**Comment by Aogon** [comment]
@ToukaiAkihiro 了解しました！これでよろしいですか？

**Comment by Aogon** [comment]
@ToukaiAkihiro 自己解決の模様です！initメソッドの引数間違えていました(^^;
お騒がせしてすみませんでした。。。
